[build]
builder = "nixpacks"

[build.env]
NIXPACKS_PHP_VERSION = "8.2"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
healthcheckTimeout = 300
